version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: chatapp_nginx
    ports:
      - "6060:80" # host:container (nginx)
    volumes:
      - ../public:/var/www/html # this maps the public folder to the nginx container
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf # this maps the nginx config file to the nginx container
    depends_on:
      - php
      - websocket

  php:
    build:
      context: ../docker/php
    container_name: chatapp_php
    volumes:
      - ../:/var/www/html

  websocket:
    build:
      context: ../docker/php
    container_name: chatapp_websocket
    entrypoint: php /var/www/html/websocket-server/server.php
    volumes:
      - ../:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: chatapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chatapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ../mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: chatapp_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: chatapp
      PMA_PASSWORD: chatapppassword
    ports:
      - "6061:80"
    depends_on:
      - mysql
