version: '3.9'

volumes:
  db_data:

services:
  nginx:
    image: nginx:latest
    container_name: chatapp_nginx
    ports:
      - "6060:80" # host:container (nginx)
    volumes:
      - ../public:/var/www/html/public # this maps the public folder to the nginx container
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf # this maps the nginx config file to the nginx container
    depends_on:
      - php
      - chatapp_websocket

  php:
    build:
      context: ./php
    container_name: chatapp_php
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql

  chatapp_websocket:
    build:
      context: ../docker/php
    container_name: chatapp_websocket
    command: ["php", "-q", "/var/www/html/websocket-server/server.php"]
    ports:
      - "6062:6062" # host:container (nginx)
    volumes:
      - ../:/var/www/html
      - ../websocket-server:/var/www/html/websocket-server


  mysql:
    image: mysql:8.0
    container_name: chatapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chatapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ../mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql # this is where the data is stored
    ports:
        - "3308:3306" # host:container (mysql)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: chatapp_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "6061:80"
    depends_on:
      - mysql
